"""add missing columns to users and other tables

Revision ID: ce4543284657
Revises: 006_add_equipment_owner_id
Create Date: 2026-09-21 13:51:00.071409
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ce4543284657'
down_revision: Union[str, None] = '006_add_equipment_owner_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('categories', sa.Column('name_tj', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('categories', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.execute('ALTER TABLE categories DROP COLUMN IF EXISTS start_date')

    op.add_column('listing_images', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.add_column('listing_images', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.execute('UPDATE listing_images SET listing_id = (SELECT equipment_id FROM listing_images li WHERE li.id = listing_images.id) WHERE listing_id IS NULL')
    op.alter_column('listing_images', 'listing_id', nullable=False)
    op.drop_index(op.f('ix_listing_images_equipment_id'), table_name='listing_images')
    op.create_index(op.f('ix_listing_images_listing_id'), 'listing_images', ['listing_id'], unique=False)
    op.drop_constraint(op.f('listing_images_equipment_id_fkey'), 'listing_images', type_='foreignkey')
    op.create_foreign_key(None, 'listing_images', 'listings', ['listing_id'], ['id'])
    op.execute('ALTER TABLE listing_images DROP COLUMN IF EXISTS equipment_id')

    op.add_column('reviews', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.execute('UPDATE reviews SET listing_id = (SELECT equipment_id FROM reviews r WHERE r.id = reviews.id) WHERE listing_id IS NULL')
    op.alter_column('reviews', 'listing_id', nullable=False)
    op.alter_column('reviews', 'booking_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f('idx_review_equipment_rating'), table_name='reviews')
    op.execute('DROP INDEX IF EXISTS ix_reviews_booking_id')
    op.execute('DROP INDEX IF EXISTS ix_reviews_equipment_id')
    op.create_index('idx_review_listing_rating', 'reviews', ['listing_id', 'rating'], unique=False)
    op.create_index(op.f('ix_reviews_listing_id'), 'reviews', ['listing_id'], unique=False)
    op.execute('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_equipment_id_fkey')
    op.create_foreign_key(None, 'reviews', 'listings', ['listing_id'], ['id'])
    op.execute('ALTER TABLE reviews DROP COLUMN IF EXISTS equipment_id')

    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('rating_sum', sa.Float(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=255), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'rating_count')
    op.drop_column('users', 'rating_sum')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone')
    op.add_column('reviews', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_equipment_id_fkey'), 'reviews', 'equipment', ['equipment_id'], ['id'])
    op.drop_index(op.f('ix_reviews_listing_id'), table_name='reviews')
    op.drop_index('idx_review_listing_rating', table_name='reviews')
    op.create_index(op.f('ix_reviews_equipment_id'), 'reviews', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('idx_review_equipment_rating'), 'reviews', ['equipment_id', 'rating'], unique=False)
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'listing_id')
    op.add_column('listing_images', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'listing_images', type_='foreignkey')
    op.create_foreign_key(op.f('listing_images_equipment_id_fkey'), 'listing_images', 'equipment', ['equipment_id'], ['id'])
    op.drop_index(op.f('ix_listing_images_listing_id'), table_name='listing_images')
    op.create_index(op.f('ix_listing_images_equipment_id'), 'listing_images', ['equipment_id'], unique=False)
    op.drop_column('listing_images', 'sort_order')
    op.drop_column('listing_images', 'listing_id')
    op.add_column('categories', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'sort_order')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'name_tj')
    # ### end Alembic commands ###
